### ISSUE TITLE
Markdown demo

### ISSUE THREAD

**Issue by brianamarie** [brianatestingthings/repository-template#3]
# GitHub flavored markdown

- [GitHub resources](#github-resources)
- [Octocats](#octocats)
- [Code examples](#code-examples)

## GitHub resources

- [GitHub.com](https://github.com)
- [GitHub on Microsoft Learn](https://docs.microsoft.com/en-us/learn/github/)

## Octocats

![Dinotocat](https://octodex.github.com/images/dinotocat.png)

> Dinotocat is one of many Octocats in the [Octodex](https://octodex.github.com/). You can build your own [here](https://myoctocat.com/)!

## Code examples

----

```yml
- name: Super-Linter
   uses: github/super-linter@v3.14.0
   env:
     VALIDATE_ALL_CODEBASE: false
     DEFAULT_BRANCH: main
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
